// ui.js
const themes = {
  Clear: { // OpenWeatherMapの晴れ
    add: ['from-orange-100', 'to-rose-200'],
    remove: ['from-blue-50', 'to-indigo-100', 'from-gray-300', 'to-slate-400']
  },
  Rain: { // OpenWeatherMapの雨
    add: ['from-gray-300', 'to-slate-400'],
    remove: ['from-blue-50', 'to-indigo-100', 'from-orange-100', 'to-rose-200']
  },
  default: { // その他（曇りなど）
    add: ['from-blue-50', 'to-indigo-100'],
    remove: ['from-orange-100', 'to-rose-200', 'from-gray-300', 'to-slate-400']
  }
};

const UI = {
  updateWeatherUI: function(data, cityName) {
    // 数値とテキストの更新
    document.getElementById("temp").innerHTML = `${Math.round(data.main.temp)}<span class="text-sm">°C</span>`;
    document.getElementById("humidity").innerHTML = `${data.main.humidity}<span class="text-sm">%</span>`;
    document.getElementById("city-name").textContent = `Generated by ${cityName} Weather`;
    
    const condition = data.weather[0].main;
    this.changeTheme(condition);
    this.updateSongTitle(condition);
  },

  changeTheme: function(condition) {
    const body = document.getElementById('app-body');
    const theme = themes[condition] || themes.default;
    
    body.classList.remove(...theme.remove);
    body.classList.add(...theme.add);
  },

  updateSongTitle: function(condition) {
    const titles = {
      Clear: '🌤️ 晴れ間のピアノ・アンビエント',
      Rain: '🌧️ 雨音とメランコリック・ギター',
      Clouds: '☁️ 雲の上のシンセサイザー'
    };
    document.getElementById('song-title').textContent = titles[condition] || '🌍 風のプロローグ';
  }
};